### ISSUE TITLE
manage.py xxxxするとエラーをはく

### ISSUE THREAD

**Issue by KissLeaRon** [KissLeaRon/lan_chatapp#2]
mizo@mizo-VirtualBox:\~/git/lan_chatapp$ python3 manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/mizo/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/mizo/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mizo/.local/lib/python3.8/site-packages/django/core/management/base.py", line 341, in run_from_argv
    connections.close_all()
  File "/home/mizo/.local/lib/python3.8/site-packages/django/db/utils.py", line 230, in close_all
    connection.close()
  File "/home/mizo/.local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/mizo/.local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 261, in close    if not self.is_in_memory_db():
  File "/home/mizo/.local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 380, in is_in_memory_db
    return self.creation.is_in_memory_db(self.settings_dict['NAME'])
  File "/home/mizo/.local/lib/python3.8/site-packages/django/db/backends/sqlite3/creation.py", line 12, in is_in_memory_db
    return database_name == ':memory:' or 'mode=memory' in database_name
TypeError: argument of type 'PosixPath' is not iterable
mizo@mizo-VirtualBox:~/git/lan_chatapp$

**Comment by KissLeaRon** [comment]
pathlib.Path使ってるのが悪いと思うんですけど(名推理)

**Comment by KissLeaRon** [comment]
おまかんっぽいです

**Comment by KissLeaRon** [comment]
解決しました。Django==3.0.2でした
